### Get all persons from phonebook
GET http://localhost:3001/api/persons

### Get info
GET http://localhost:3001/info

### Add a person to phonebook
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Jonathan Van de Vyver",
    "callnumber": "047805-69325"
}